from __future__ import annotations

import uuid
from datetime import datetime
from typing import Annotated, Any

from fastapi import Query
from pydantic import BaseModel, ConfigDict, Field

from app.models.enums import AutonomyLevel, RiskTier, SystemStatus
from app.schemas.common import ORMModel


class SystemMetadataBase(BaseModel):
    purpose: str | None = Field(default=None, examples=["Screen job applicants for shortlisting"])
    use_case: str | None = Field(default=None, examples=["employment_screening"])
    industry: str | None = Field(default=None, examples=["hr_tech"])
    autonomy_level: AutonomyLevel = AutonomyLevel.HUMAN_IN_THE_LOOP
    data_categories: list[str] = Field(
        default_factory=list, examples=[["personal_data", "employment_history"]]
    )
    deployment_regions: list[str] = Field(default_factory=list, examples=[["EU", "US-CA"]])
    data_subject_regions: list[str] = Field(default_factory=list, examples=[["EU", "IN"]])
    data_residency: list[str] = Field(default_factory=list, examples=[["EU"]])
    offered_in_regions: list[str] = Field(
        default_factory=list,
        description="Markets the system is offered or marketed to.",
        examples=[["EU", "US-CA"]],
    )
    service_accessible_regions: list[str] = Field(
        default_factory=list,
        description="Where the service can be reached. Use GLOBAL for the public internet.",
        examples=[["GLOBAL"]],
    )
    content_accessible_regions: list[str] = Field(
        default_factory=list,
        description="Where output generated by the system can be viewed.",
        examples=[["GLOBAL"]],
    )
    third_party_models: list[str] = Field(default_factory=list, examples=[["claude-opus-5"]])
    affects_minors: bool = False
    uses_biometrics: bool = False
    uses_generative_ai: bool = False
    is_safety_component: bool = False
    makes_automated_decisions: bool = False
    human_oversight_documented: bool = False
    conformity_assessment_done: bool = False
    technical_documentation_url: str | None = None
    training_data_documented: bool = False
    incident_response_plan: bool = False
    attributes: dict[str, Any] = Field(default_factory=dict)


class SystemMetadataUpdate(BaseModel):
    """All fields optional for PATCH semantics."""

    model_config = ConfigDict(extra="forbid")

    purpose: str | None = None
    use_case: str | None = None
    industry: str | None = None
    autonomy_level: AutonomyLevel | None = None
    data_categories: list[str] | None = None
    deployment_regions: list[str] | None = None
    data_subject_regions: list[str] | None = None
    data_residency: list[str] | None = None
    offered_in_regions: list[str] | None = None
    service_accessible_regions: list[str] | None = None
    content_accessible_regions: list[str] | None = None
    third_party_models: list[str] | None = None
    affects_minors: bool | None = None
    uses_biometrics: bool | None = None
    uses_generative_ai: bool | None = None
    is_safety_component: bool | None = None
    makes_automated_decisions: bool | None = None
    human_oversight_documented: bool | None = None
    conformity_assessment_done: bool | None = None
    technical_documentation_url: str | None = None
    training_data_documented: bool | None = None
    incident_response_plan: bool | None = None
    attributes: dict[str, Any] | None = None


class SystemMetadataRead(ORMModel, SystemMetadataBase):
    id: uuid.UUID
    updated_at: datetime


class AISystemCreate(BaseModel):
    name: str = Field(min_length=1, max_length=255, examples=["Resume Screening Assistant"])
    description: str | None = Field(default=None, examples=["Ranks applicants for recruiters."])
    owner_id: uuid.UUID | None = Field(
        default=None, description="Defaults to the authenticated user."
    )
    status: SystemStatus = SystemStatus.DRAFT
    metadata: dict[str, Any] = Field(default_factory=dict, alias="metadata")
    system_metadata: SystemMetadataBase = Field(default_factory=SystemMetadataBase)

    model_config = ConfigDict(populate_by_name=True)


class AISystemUpdate(BaseModel):
    name: str | None = Field(default=None, min_length=1, max_length=255)
    description: str | None = None
    owner_id: uuid.UUID | None = None
    status: SystemStatus | None = None
    metadata: dict[str, Any] | None = None
    system_metadata: SystemMetadataUpdate | None = None
    change_summary: str | None = Field(default=None, max_length=500)

    model_config = ConfigDict(populate_by_name=True)


class OwnerRead(ORMModel):
    id: uuid.UUID
    email: str
    full_name: str


class AISystemRead(ORMModel):
    id: uuid.UUID
    name: str
    description: str | None
    owner_id: uuid.UUID
    owner: OwnerRead | None = None
    status: SystemStatus
    metadata_version: int
    extra_metadata: dict[str, Any] = Field(serialization_alias="metadata")
    system_metadata: SystemMetadataRead | None = None
    created_at: datetime
    updated_at: datetime


class AISystemSummary(ORMModel):
    id: uuid.UUID
    name: str
    status: SystemStatus
    owner_id: uuid.UUID
    updated_at: datetime


class SystemVersionRead(ORMModel):
    id: uuid.UUID
    version: int
    changed_by_id: uuid.UUID | None
    change_summary: str | None
    snapshot: dict[str, Any]
    diff: dict[str, Any]
    created_at: datetime


class SystemFilters(BaseModel):
    """Advanced inventory filtering."""

    q: str | None = None
    status: list[SystemStatus] | None = None
    owner_id: uuid.UUID | None = None
    jurisdiction: list[str] | None = None
    risk_tier: list[RiskTier] | None = None
    industry: str | None = None
    use_case: str | None = None
    deployment_region: str | None = None
    uses_generative_ai: bool | None = None
    include_deleted: bool = False


def system_filters(
    q: Annotated[
        str | None, Query(description="Free-text search on name/description/purpose")
    ] = None,
    status: Annotated[list[SystemStatus] | None, Query()] = None,
    owner_id: Annotated[uuid.UUID | None, Query()] = None,
    jurisdiction: Annotated[
        list[str] | None, Query(description="Filter by latest-classification jurisdiction code")
    ] = None,
    risk_tier: Annotated[list[RiskTier] | None, Query()] = None,
    industry: Annotated[str | None, Query()] = None,
    use_case: Annotated[str | None, Query()] = None,
    deployment_region: Annotated[str | None, Query()] = None,
    uses_generative_ai: Annotated[bool | None, Query()] = None,
    include_deleted: Annotated[bool, Query()] = False,
) -> SystemFilters:
    return SystemFilters(
        q=q,
        status=status,
        owner_id=owner_id,
        jurisdiction=jurisdiction,
        risk_tier=risk_tier,
        industry=industry,
        use_case=use_case,
        deployment_region=deployment_region,
        uses_generative_ai=uses_generative_ai,
        include_deleted=include_deleted,
    )
